apiVersion: apps/v1
kind: Ingress
metadata:
  name:  static-website
  labels:
    name: 
spec:
  rules:
  - host: kubernetes.lekkalahyma.xyz
    http:
      paths:
      - pathType: 
        path: 
        backend:
          service:
            name: static-svc
            port: 
              number: 80
